#!/usr/bin/env bash
set -uo pipefail

usage() {
  cat <<'USAGE'
Load table-level checkpoint dump outputs into a MatrixOne tenant.

The script scans dump output directories generated by dump_ckp_tables.sh, executes
each restore.sql, and writes per-table logs plus a summary.

Usage:
  ./load_ckp_table_dumps.sh [options]

Options:
  --host HOST             MySQL host, default: 127.0.0.1
  --port PORT             MySQL port, default: 6001
  --user USER             MySQL user, e.g. acc01:test_account
  --password PASSWORD     MySQL password
  --dump-root DIR         Dump root, default: /data4/weilu/ckp_test
  --log-dir DIR           Log dir, default: <dump-root>/load_logs_<timestamp>
  --drop-target-dbs       Drop ckp_* target databases before loading
  --force                 Use mysql --force so one SQL error does not abort a file
  --only-db DB            Load only one dumped database, e.g. ckp_types
  --help                  Show this help

Examples:
  ./load_ckp_table_dumps.sh --user acc01:test_account --password 111 --drop-target-dbs
  ./load_ckp_table_dumps.sh --host 172.16.96.178 --user acc01:test_account --password 111 --only-db ckp_types
USAGE
}

HOST="127.0.0.1"
PORT="6001"
USER=""
PASSWORD=""
DUMP_ROOT="/data4/weilu/ckp_test"
TS="$(date +%Y%m%d_%H%M%S)"
LOG_DIR=""
DROP_TARGET_DBS="0"
MYSQL_FORCE="0"
ONLY_DB=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --host) HOST="$2"; shift 2 ;;
    --port) PORT="$2"; shift 2 ;;
    --user) USER="$2"; shift 2 ;;
    --password) PASSWORD="$2"; shift 2 ;;
    --dump-root) DUMP_ROOT="$2"; shift 2 ;;
    --log-dir) LOG_DIR="$2"; shift 2 ;;
    --drop-target-dbs) DROP_TARGET_DBS="1"; shift ;;
    --force) MYSQL_FORCE="1"; shift ;;
    --only-db) ONLY_DB="$2"; shift 2 ;;
    --help|-h) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage; exit 2 ;;
  esac
done

if [[ -z "$USER" || -z "$PASSWORD" ]]; then
  echo "--user and --password are required" >&2
  usage
  exit 2
fi

if [[ ! -d "$DUMP_ROOT" ]]; then
  echo "dump root does not exist: $DUMP_ROOT" >&2
  exit 1
fi

if [[ -z "$LOG_DIR" ]]; then
  LOG_DIR="$DUMP_ROOT/load_logs_$TS"
fi
mkdir -p "$LOG_DIR"

mysql_args=(
  -h"$HOST"
  -P"$PORT"
  -u"$USER"
  --default-character-set=utf8mb4
  --binary-mode=1
  --show-warnings
)
if [[ "$MYSQL_FORCE" == "1" ]]; then
  mysql_args+=(--force)
fi

run_mysql_sql() {
  local sql="$1"
  MYSQL_PWD="$PASSWORD" mysql "${mysql_args[@]}" -e "$sql"
}

if [[ "$DROP_TARGET_DBS" == "1" ]]; then
  echo "==> Dropping target ckp_* databases on $HOST:$PORT as $USER"
  run_mysql_sql "DROP DATABASE IF EXISTS ckp_types; DROP DATABASE IF EXISTS ckp_constraints; DROP DATABASE IF EXISTS ckp_tables; DROP DATABASE IF EXISTS ckp_mvcc_perf;"
fi

summary="$LOG_DIR/summary.tsv"
missing="$LOG_DIR/missing_restore_sql.tsv"
invalid="$LOG_DIR/invalid_restore_sql.tsv"
: > "$summary"
: > "$missing"
: > "$invalid"
printf "db\ttable_dir\trestore_sql\tstatus\tlog\n" >> "$summary"
printf "db\ttable_dir\n" >> "$missing"
printf "db\ttable_dir\trestore_sql\treason\n" >> "$invalid"

echo "==> Loading dumps from $DUMP_ROOT"
echo "==> Logs: $LOG_DIR"

db_dirs=()
for db_path in "$DUMP_ROOT"/ckp_*; do
  [[ -d "$db_path" ]] || continue
  db="$(basename "$db_path")"
  [[ "$db" == logs || "$db" == load_logs_* ]] && continue
  if [[ -n "$ONLY_DB" && "$db" != "$ONLY_DB" ]]; then
    continue
  fi
  db_dirs+=("$db_path")
done

if [[ ${#db_dirs[@]} -eq 0 ]]; then
  echo "No ckp_* dump directories found under $DUMP_ROOT" >&2
  exit 1
fi

total=0
ok=0
fail=0
missing_count=0

for db_path in "${db_dirs[@]}"; do
  db="$(basename "$db_path")"
  echo "==> Database group: $db"

  for table_path in "$db_path"/*; do
    [[ -d "$table_path" ]] || continue
    table_dir="$(basename "$table_path")"
    restore="$table_path/restore.sql"

    if [[ ! -f "$restore" ]]; then
      echo "MISS $db/$table_dir: restore.sql not found"
      printf "%s\t%s\n" "$db" "$table_dir" >> "$missing"
      missing_count=$((missing_count + 1))
      continue
    fi

    if ! grep -q "CREATE TABLE" "$restore" || ! grep -q "LOAD DATA" "$restore"; then
      echo "INVALID $db/$table_dir: restore.sql has no CREATE TABLE or LOAD DATA"
      printf "%s\t%s\t%s\t%s\n" "$db" "$table_dir" "$restore" "missing CREATE TABLE or LOAD DATA" >> "$invalid"
      missing_count=$((missing_count + 1))
      continue
    fi

    if python3 - "$restore" <<'PY'
import pathlib
import sys
data = pathlib.Path(sys.argv[1]).read_bytes()
sys.exit(0 if b"\x00" in data else 1)
PY
    then
      echo "INVALID $db/$table_dir: restore.sql contains NUL bytes"
      printf "%s\t%s\t%s\t%s\n" "$db" "$table_dir" "$restore" "contains NUL bytes" >> "$invalid"
      missing_count=$((missing_count + 1))
      continue
    fi

    total=$((total + 1))
    log="$LOG_DIR/${db}__${table_dir}.log"
    echo "LOAD $db/$table_dir"

    (
      echo "LOAD_START $(date '+%Y-%m-%d %H:%M:%S')"
      echo "restore_sql=$restore"
      /usr/bin/time -v env MYSQL_PWD="$PASSWORD" mysql "${mysql_args[@]}" < "$restore"
      rc=$?
      echo "LOAD_END $(date '+%Y-%m-%d %H:%M:%S')"
      echo "LOAD_EXIT_STATUS $rc"
      exit "$rc"
    ) > "$log" 2>&1
    rc=$?

    if [[ "$rc" -eq 0 ]]; then
      ok=$((ok + 1))
      printf "%s\t%s\t%s\tOK\t%s\n" "$db" "$table_dir" "$restore" "$log" >> "$summary"
    else
      fail=$((fail + 1))
      printf "%s\t%s\t%s\tFAIL\t%s\n" "$db" "$table_dir" "$restore" "$log" >> "$summary"
      echo "FAIL $db/$table_dir, see $log"
    fi
  done
done

echo "==> Load summary"
echo "restore_sql attempted: $total"
echo "success: $ok"
echo "failed: $fail"
echo "missing restore.sql: $missing_count"
echo "summary: $summary"
echo "missing: $missing"
echo "invalid: $invalid"

echo "==> Target table counts"
MYSQL_PWD="$PASSWORD" mysql "${mysql_args[@]}" -e "
SELECT table_schema, COUNT(*) AS table_count
FROM information_schema.tables
WHERE table_schema IN ('ckp_types','ckp_constraints','ckp_tables','ckp_mvcc_perf')
GROUP BY table_schema
ORDER BY table_schema;
" 2>&1 | tee "$LOG_DIR/target_table_counts.log"
